version: '3.9'

services:
  qdrant:
    container_name: qdrant-container
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"   # gRPC도 노출할 경우
    volumes:
      - qdrant-data:/qdrant/storage

volumes:
  qdrant-data:

